/*
Galasa Ecosystem API

The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.

API version: 0.37.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package galasaapi

import (
	"encoding/json"
)

// checks if the GalasaPropertyData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GalasaPropertyData{}

// GalasaPropertyData struct for GalasaPropertyData
type GalasaPropertyData struct {
	// The value of the property, maximum length of approximately 1,500,000 characters. It cannot be a blank value. 
	Value *string `json:"value,omitempty"`
}

// NewGalasaPropertyData instantiates a new GalasaPropertyData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGalasaPropertyData() *GalasaPropertyData {
	this := GalasaPropertyData{}
	return &this
}

// NewGalasaPropertyDataWithDefaults instantiates a new GalasaPropertyData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGalasaPropertyDataWithDefaults() *GalasaPropertyData {
	this := GalasaPropertyData{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GalasaPropertyData) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GalasaPropertyData) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GalasaPropertyData) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GalasaPropertyData) SetValue(v string) {
	o.Value = &v
}

func (o GalasaPropertyData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GalasaPropertyData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableGalasaPropertyData struct {
	value *GalasaPropertyData
	isSet bool
}

func (v NullableGalasaPropertyData) Get() *GalasaPropertyData {
	return v.value
}

func (v *NullableGalasaPropertyData) Set(val *GalasaPropertyData) {
	v.value = val
	v.isSet = true
}

func (v NullableGalasaPropertyData) IsSet() bool {
	return v.isSet
}

func (v *NullableGalasaPropertyData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGalasaPropertyData(val *GalasaPropertyData) *NullableGalasaPropertyData {
	return &NullableGalasaPropertyData{value: val, isSet: true}
}

func (v NullableGalasaPropertyData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGalasaPropertyData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


