/*
Galasa Ecosystem API

The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.

API version: 0.37.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg/galasaapi

import (
	"encoding/json"
)

// checks if the CpsProperty type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CpsProperty{}

// CpsProperty struct for CpsProperty
type CpsProperty struct {
	// The fully-qualified property name, including the 'namespace'.
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewCpsProperty instantiates a new CpsProperty object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpsProperty() *CpsProperty {
	this := CpsProperty{}
	return &this
}

// NewCpsPropertyWithDefaults instantiates a new CpsProperty object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpsPropertyWithDefaults() *CpsProperty {
	this := CpsProperty{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CpsProperty) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CpsProperty) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CpsProperty) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CpsProperty) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CpsProperty) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CpsProperty) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CpsProperty) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CpsProperty) SetValue(v string) {
	o.Value = &v
}

func (o CpsProperty) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CpsProperty) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableCpsProperty struct {
	value *CpsProperty
	isSet bool
}

func (v NullableCpsProperty) Get() *CpsProperty {
	return v.value
}

func (v *NullableCpsProperty) Set(val *CpsProperty) {
	v.value = val
	v.isSet = true
}

func (v NullableCpsProperty) IsSet() bool {
	return v.isSet
}

func (v *NullableCpsProperty) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpsProperty(val *CpsProperty) *NullableCpsProperty {
	return &NullableCpsProperty{value: val, isSet: true}
}

func (v NullableCpsProperty) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpsProperty) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


