/*
Galasa Ecosystem API

The Galasa Ecosystem REST API allows you to interact with a Galasa Ecosystem.

API version: 0.37.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package pkg/galasaapi

import (
	"encoding/json"
)

// checks if the TestRun type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestRun{}

// TestRun struct for TestRun
type TestRun struct {
	Name *string `json:"name,omitempty"`
	Type *string `json:"type,omitempty"`
	Group *string `json:"group,omitempty"`
	Test *string `json:"test,omitempty"`
	BundleName *string `json:"bundleName,omitempty"`
	TestName *string `json:"testName,omitempty"`
	Status *string `json:"status,omitempty"`
	Result *string `json:"result,omitempty"`
	Queued *string `json:"queued,omitempty"`
	Requestor *string `json:"requestor,omitempty"`
	Stream *string `json:"stream,omitempty"`
	Repo *string `json:"repo,omitempty"`
	Obr *string `json:"obr,omitempty"`
	Rerun *bool `json:"rerun,omitempty"`
	RerunReason *string `json:"rerunReason,omitempty"`
	Local *bool `json:"local,omitempty"`
	Trace *bool `json:"trace,omitempty"`
	RasRunId *string `json:"rasRunId,omitempty"`
}

// NewTestRun instantiates a new TestRun object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestRun() *TestRun {
	this := TestRun{}
	return &this
}

// NewTestRunWithDefaults instantiates a new TestRun object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestRunWithDefaults() *TestRun {
	this := TestRun{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *TestRun) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *TestRun) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *TestRun) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TestRun) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TestRun) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TestRun) SetType(v string) {
	o.Type = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *TestRun) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *TestRun) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *TestRun) SetGroup(v string) {
	o.Group = &v
}

// GetTest returns the Test field value if set, zero value otherwise.
func (o *TestRun) GetTest() string {
	if o == nil || IsNil(o.Test) {
		var ret string
		return ret
	}
	return *o.Test
}

// GetTestOk returns a tuple with the Test field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetTestOk() (*string, bool) {
	if o == nil || IsNil(o.Test) {
		return nil, false
	}
	return o.Test, true
}

// HasTest returns a boolean if a field has been set.
func (o *TestRun) HasTest() bool {
	if o != nil && !IsNil(o.Test) {
		return true
	}

	return false
}

// SetTest gets a reference to the given string and assigns it to the Test field.
func (o *TestRun) SetTest(v string) {
	o.Test = &v
}

// GetBundleName returns the BundleName field value if set, zero value otherwise.
func (o *TestRun) GetBundleName() string {
	if o == nil || IsNil(o.BundleName) {
		var ret string
		return ret
	}
	return *o.BundleName
}

// GetBundleNameOk returns a tuple with the BundleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetBundleNameOk() (*string, bool) {
	if o == nil || IsNil(o.BundleName) {
		return nil, false
	}
	return o.BundleName, true
}

// HasBundleName returns a boolean if a field has been set.
func (o *TestRun) HasBundleName() bool {
	if o != nil && !IsNil(o.BundleName) {
		return true
	}

	return false
}

// SetBundleName gets a reference to the given string and assigns it to the BundleName field.
func (o *TestRun) SetBundleName(v string) {
	o.BundleName = &v
}

// GetTestName returns the TestName field value if set, zero value otherwise.
func (o *TestRun) GetTestName() string {
	if o == nil || IsNil(o.TestName) {
		var ret string
		return ret
	}
	return *o.TestName
}

// GetTestNameOk returns a tuple with the TestName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetTestNameOk() (*string, bool) {
	if o == nil || IsNil(o.TestName) {
		return nil, false
	}
	return o.TestName, true
}

// HasTestName returns a boolean if a field has been set.
func (o *TestRun) HasTestName() bool {
	if o != nil && !IsNil(o.TestName) {
		return true
	}

	return false
}

// SetTestName gets a reference to the given string and assigns it to the TestName field.
func (o *TestRun) SetTestName(v string) {
	o.TestName = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TestRun) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TestRun) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *TestRun) SetStatus(v string) {
	o.Status = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *TestRun) GetResult() string {
	if o == nil || IsNil(o.Result) {
		var ret string
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetResultOk() (*string, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *TestRun) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given string and assigns it to the Result field.
func (o *TestRun) SetResult(v string) {
	o.Result = &v
}

// GetQueued returns the Queued field value if set, zero value otherwise.
func (o *TestRun) GetQueued() string {
	if o == nil || IsNil(o.Queued) {
		var ret string
		return ret
	}
	return *o.Queued
}

// GetQueuedOk returns a tuple with the Queued field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetQueuedOk() (*string, bool) {
	if o == nil || IsNil(o.Queued) {
		return nil, false
	}
	return o.Queued, true
}

// HasQueued returns a boolean if a field has been set.
func (o *TestRun) HasQueued() bool {
	if o != nil && !IsNil(o.Queued) {
		return true
	}

	return false
}

// SetQueued gets a reference to the given string and assigns it to the Queued field.
func (o *TestRun) SetQueued(v string) {
	o.Queued = &v
}

// GetRequestor returns the Requestor field value if set, zero value otherwise.
func (o *TestRun) GetRequestor() string {
	if o == nil || IsNil(o.Requestor) {
		var ret string
		return ret
	}
	return *o.Requestor
}

// GetRequestorOk returns a tuple with the Requestor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetRequestorOk() (*string, bool) {
	if o == nil || IsNil(o.Requestor) {
		return nil, false
	}
	return o.Requestor, true
}

// HasRequestor returns a boolean if a field has been set.
func (o *TestRun) HasRequestor() bool {
	if o != nil && !IsNil(o.Requestor) {
		return true
	}

	return false
}

// SetRequestor gets a reference to the given string and assigns it to the Requestor field.
func (o *TestRun) SetRequestor(v string) {
	o.Requestor = &v
}

// GetStream returns the Stream field value if set, zero value otherwise.
func (o *TestRun) GetStream() string {
	if o == nil || IsNil(o.Stream) {
		var ret string
		return ret
	}
	return *o.Stream
}

// GetStreamOk returns a tuple with the Stream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetStreamOk() (*string, bool) {
	if o == nil || IsNil(o.Stream) {
		return nil, false
	}
	return o.Stream, true
}

// HasStream returns a boolean if a field has been set.
func (o *TestRun) HasStream() bool {
	if o != nil && !IsNil(o.Stream) {
		return true
	}

	return false
}

// SetStream gets a reference to the given string and assigns it to the Stream field.
func (o *TestRun) SetStream(v string) {
	o.Stream = &v
}

// GetRepo returns the Repo field value if set, zero value otherwise.
func (o *TestRun) GetRepo() string {
	if o == nil || IsNil(o.Repo) {
		var ret string
		return ret
	}
	return *o.Repo
}

// GetRepoOk returns a tuple with the Repo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetRepoOk() (*string, bool) {
	if o == nil || IsNil(o.Repo) {
		return nil, false
	}
	return o.Repo, true
}

// HasRepo returns a boolean if a field has been set.
func (o *TestRun) HasRepo() bool {
	if o != nil && !IsNil(o.Repo) {
		return true
	}

	return false
}

// SetRepo gets a reference to the given string and assigns it to the Repo field.
func (o *TestRun) SetRepo(v string) {
	o.Repo = &v
}

// GetObr returns the Obr field value if set, zero value otherwise.
func (o *TestRun) GetObr() string {
	if o == nil || IsNil(o.Obr) {
		var ret string
		return ret
	}
	return *o.Obr
}

// GetObrOk returns a tuple with the Obr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetObrOk() (*string, bool) {
	if o == nil || IsNil(o.Obr) {
		return nil, false
	}
	return o.Obr, true
}

// HasObr returns a boolean if a field has been set.
func (o *TestRun) HasObr() bool {
	if o != nil && !IsNil(o.Obr) {
		return true
	}

	return false
}

// SetObr gets a reference to the given string and assigns it to the Obr field.
func (o *TestRun) SetObr(v string) {
	o.Obr = &v
}

// GetRerun returns the Rerun field value if set, zero value otherwise.
func (o *TestRun) GetRerun() bool {
	if o == nil || IsNil(o.Rerun) {
		var ret bool
		return ret
	}
	return *o.Rerun
}

// GetRerunOk returns a tuple with the Rerun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetRerunOk() (*bool, bool) {
	if o == nil || IsNil(o.Rerun) {
		return nil, false
	}
	return o.Rerun, true
}

// HasRerun returns a boolean if a field has been set.
func (o *TestRun) HasRerun() bool {
	if o != nil && !IsNil(o.Rerun) {
		return true
	}

	return false
}

// SetRerun gets a reference to the given bool and assigns it to the Rerun field.
func (o *TestRun) SetRerun(v bool) {
	o.Rerun = &v
}

// GetRerunReason returns the RerunReason field value if set, zero value otherwise.
func (o *TestRun) GetRerunReason() string {
	if o == nil || IsNil(o.RerunReason) {
		var ret string
		return ret
	}
	return *o.RerunReason
}

// GetRerunReasonOk returns a tuple with the RerunReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetRerunReasonOk() (*string, bool) {
	if o == nil || IsNil(o.RerunReason) {
		return nil, false
	}
	return o.RerunReason, true
}

// HasRerunReason returns a boolean if a field has been set.
func (o *TestRun) HasRerunReason() bool {
	if o != nil && !IsNil(o.RerunReason) {
		return true
	}

	return false
}

// SetRerunReason gets a reference to the given string and assigns it to the RerunReason field.
func (o *TestRun) SetRerunReason(v string) {
	o.RerunReason = &v
}

// GetLocal returns the Local field value if set, zero value otherwise.
func (o *TestRun) GetLocal() bool {
	if o == nil || IsNil(o.Local) {
		var ret bool
		return ret
	}
	return *o.Local
}

// GetLocalOk returns a tuple with the Local field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetLocalOk() (*bool, bool) {
	if o == nil || IsNil(o.Local) {
		return nil, false
	}
	return o.Local, true
}

// HasLocal returns a boolean if a field has been set.
func (o *TestRun) HasLocal() bool {
	if o != nil && !IsNil(o.Local) {
		return true
	}

	return false
}

// SetLocal gets a reference to the given bool and assigns it to the Local field.
func (o *TestRun) SetLocal(v bool) {
	o.Local = &v
}

// GetTrace returns the Trace field value if set, zero value otherwise.
func (o *TestRun) GetTrace() bool {
	if o == nil || IsNil(o.Trace) {
		var ret bool
		return ret
	}
	return *o.Trace
}

// GetTraceOk returns a tuple with the Trace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetTraceOk() (*bool, bool) {
	if o == nil || IsNil(o.Trace) {
		return nil, false
	}
	return o.Trace, true
}

// HasTrace returns a boolean if a field has been set.
func (o *TestRun) HasTrace() bool {
	if o != nil && !IsNil(o.Trace) {
		return true
	}

	return false
}

// SetTrace gets a reference to the given bool and assigns it to the Trace field.
func (o *TestRun) SetTrace(v bool) {
	o.Trace = &v
}

// GetRasRunId returns the RasRunId field value if set, zero value otherwise.
func (o *TestRun) GetRasRunId() string {
	if o == nil || IsNil(o.RasRunId) {
		var ret string
		return ret
	}
	return *o.RasRunId
}

// GetRasRunIdOk returns a tuple with the RasRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestRun) GetRasRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.RasRunId) {
		return nil, false
	}
	return o.RasRunId, true
}

// HasRasRunId returns a boolean if a field has been set.
func (o *TestRun) HasRasRunId() bool {
	if o != nil && !IsNil(o.RasRunId) {
		return true
	}

	return false
}

// SetRasRunId gets a reference to the given string and assigns it to the RasRunId field.
func (o *TestRun) SetRasRunId(v string) {
	o.RasRunId = &v
}

func (o TestRun) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestRun) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.Test) {
		toSerialize["test"] = o.Test
	}
	if !IsNil(o.BundleName) {
		toSerialize["bundleName"] = o.BundleName
	}
	if !IsNil(o.TestName) {
		toSerialize["testName"] = o.TestName
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Queued) {
		toSerialize["queued"] = o.Queued
	}
	if !IsNil(o.Requestor) {
		toSerialize["requestor"] = o.Requestor
	}
	if !IsNil(o.Stream) {
		toSerialize["stream"] = o.Stream
	}
	if !IsNil(o.Repo) {
		toSerialize["repo"] = o.Repo
	}
	if !IsNil(o.Obr) {
		toSerialize["obr"] = o.Obr
	}
	if !IsNil(o.Rerun) {
		toSerialize["rerun"] = o.Rerun
	}
	if !IsNil(o.RerunReason) {
		toSerialize["rerunReason"] = o.RerunReason
	}
	if !IsNil(o.Local) {
		toSerialize["local"] = o.Local
	}
	if !IsNil(o.Trace) {
		toSerialize["trace"] = o.Trace
	}
	if !IsNil(o.RasRunId) {
		toSerialize["rasRunId"] = o.RasRunId
	}
	return toSerialize, nil
}

type NullableTestRun struct {
	value *TestRun
	isSet bool
}

func (v NullableTestRun) Get() *TestRun {
	return v.value
}

func (v *NullableTestRun) Set(val *TestRun) {
	v.value = val
	v.isSet = true
}

func (v NullableTestRun) IsSet() bool {
	return v.isSet
}

func (v *NullableTestRun) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestRun(val *TestRun) *NullableTestRun {
	return &NullableTestRun{value: val, isSet: true}
}

func (v NullableTestRun) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestRun) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


